/*-------------------------------------------------------------------------
 *
 * wait_event_timing_data.c
 *    Generated wait events infrastructure code
 *
 * Portions Copyright (c) 1996-2026, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/utils/activity/generate-wait_event_types.pl
 *
 *-------------------------------------------------------------------------
 */

static const int8 wait_event_class_dense[WAIT_EVENT_TIMING_RAW_CLASSES] = {
	-1,		/* 0x00: unused */
	-1,		/* 0x01: LWLock (uses hash) */
	-1,		/* 0x02: unused */
	 0,		/* 0x03: Lock */
	 1,		/* 0x04: Buffer */
	 2,		/* 0x05: Activity */
	 3,		/* 0x06: Client */
	 4,		/* 0x07: Extension */
	 5,		/* 0x08: IPC */
	 6,		/* 0x09: Timeout */
	 7,		/* 0x0a: IO */
	 8		/* 0x0b: InjectionPoint */
};

static const int wait_event_class_nevents[WAIT_EVENT_TIMING_DENSE_CLASSES] = {
	16,		/* Lock (actual: 12) */
	16,		/* Buffer (actual: 4) */
	32,		/* Activity (actual: 18) */
	16,		/* Client (actual: 12) */
	128,		/* Extension (actual: 1) */
	64,		/* IPC (actual: 57) */
	16,		/* Timeout (actual: 11) */
	128,		/* IO (actual: 83) */
	128		/* InjectionPoint (actual: 0) */
};

static const int wait_event_class_offset[WAIT_EVENT_TIMING_DENSE_CLASSES] = {
	0,		/* Lock */
	16,		/* Buffer */
	32,		/* Activity */
	64,		/* Client */
	80,		/* Extension */
	208,		/* IPC */
	272,		/* Timeout */
	288,		/* IO */
	416		/* InjectionPoint */
};

static const uint8 wait_event_dense_to_classid[WAIT_EVENT_TIMING_DENSE_CLASSES] = {
	0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b
};
